config/routes.rb
Bolao::Application.routes.draw do
  resources :classificacaos

  resources :palpites

  resources :usuarios

  resources :jogos

  resources :clubes
	
  get "home/index"
  get "bolao" => 'bolao#index'

    root :to => 'home#index'

end

app/models/classificacao.rb
class Classificacao < ActiveRecord::Base
  attr_accessible :derrotas, :empates, :gols, :golscontra, :id_time, :jogos, :pontos, :saldogols, :vitorias
end

app/controllers/classificacaos_controller.rb
class ClassificacaosController < ApplicationController
  # GET /classificacaos
  # GET /classificacaos.json
  def index
    @classificacaos = Classificacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @classificacaos }
    end
  end

  # GET /classificacaos/1
  # GET /classificacaos/1.json
  def show
    @classificacao = Classificacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @classificacao }
    end
  end

  # GET /classificacaos/new
  # GET /classificacaos/new.json
  def new
    @classificacao = Classificacao.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @classificacao }
    end
  end

  # GET /classificacaos/1/edit
  def edit
    @classificacao = Classificacao.find(params[:id])
  end

  # POST /classificacaos
  # POST /classificacaos.json
  def create
    @classificacao = Classificacao.new(params[:classificacao])

    respond_to do |format|
      if @classificacao.save
        format.html { redirect_to @classificacao, :notice => 'Classificacao was successfully created.' }
        format.json { render :json => @classificacao, :status => :created, :location => @classificacao }
      else
        format.html { render :action => "new" }
        format.json { render :json => @classificacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /classificacaos/1
  # PUT /classificacaos/1.json
  def update
    @classificacao = Classificacao.find(params[:id])

    respond_to do |format|
      if @classificacao.update_attributes(params[:classificacao])
        format.html { redirect_to @classificacao, :notice => 'Classificacao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @classificacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /classificacaos/1
  # DELETE /classificacaos/1.json
  def destroy
    @classificacao = Classificacao.find(params[:id])
    @classificacao.destroy

    respond_to do |format|
      format.html { redirect_to classificacaos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/classificacaos_helper.rb
module ClassificacaosHelper
end

app/views/classificacaos/_form.html.erb
<%= form_for(@classificacao) do |f| %>
  <% if @classificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classificacao.errors.count, "error") %> prohibited this classificacao from being saved:</h2>

      <ul>
      <% @classificacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_time %><br />
    <%= f.number_field :id_time %>
  </div>
  <div class="field">
    <%= f.label :pontos %><br />
    <%= f.number_field :pontos %>
  </div>
  <div class="field">
    <%= f.label :jogos %><br />
    <%= f.number_field :jogos %>
  </div>
  <div class="field">
    <%= f.label :vitorias %><br />
    <%= f.number_field :vitorias %>
  </div>
  <div class="field">
    <%= f.label :empates %><br />
    <%= f.number_field :empates %>
  </div>
  <div class="field">
    <%= f.label :derrotas %><br />
    <%= f.number_field :derrotas %>
  </div>
  <div class="field">
    <%= f.label :gols %><br />
    <%= f.number_field :gols %>
  </div>
  <div class="field">
    <%= f.label :golscontra %><br />
    <%= f.number_field :golscontra %>
  </div>
  <div class="field">
    <%= f.label :saldogols %><br />
    <%= f.number_field :saldogols %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classificacaos/edit.html.erb
<h1>Editing classificacao</h1>

<%= render 'form' %>

<%= link_to 'Show', @classificacao %> |
<%= link_to 'Back', classificacaos_path %>

app/views/classificacaos/index.html.erb
<h1>Listing classificacaos</h1>

<table>
  <tr>
    <th>Id time</th>
    <th>Pontos</th>
    <th>Jogos</th>
    <th>Vitorias</th>
    <th>Empates</th>
    <th>Derrotas</th>
    <th>Gols</th>
    <th>Golscontra</th>
    <th>Saldogols</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @classificacaos.each do |classificacao| %>
  <tr>
    <td><%= classificacao.id_time %></td>
    <td><%= classificacao.pontos %></td>
    <td><%= classificacao.jogos %></td>
    <td><%= classificacao.vitorias %></td>
    <td><%= classificacao.empates %></td>
    <td><%= classificacao.derrotas %></td>
    <td><%= classificacao.gols %></td>
    <td><%= classificacao.golscontra %></td>
    <td><%= classificacao.saldogols %></td>
    <td><%= link_to 'Show', classificacao %></td>
    <td><%= link_to 'Edit', edit_classificacao_path(classificacao) %></td>
    <td><%= link_to 'Destroy', classificacao, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Classificacao', new_classificacao_path %>

app/views/classificacaos/new.html.erb
<h1>New classificacao</h1>

<%= render 'form' %>

<%= link_to 'Back', classificacaos_path %>

app/views/classificacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id time:</b>
  <%= @classificacao.id_time %>
</p>

<p>
  <b>Pontos:</b>
  <%= @classificacao.pontos %>
</p>

<p>
  <b>Jogos:</b>
  <%= @classificacao.jogos %>
</p>

<p>
  <b>Vitorias:</b>
  <%= @classificacao.vitorias %>
</p>

<p>
  <b>Empates:</b>
  <%= @classificacao.empates %>
</p>

<p>
  <b>Derrotas:</b>
  <%= @classificacao.derrotas %>
</p>

<p>
  <b>Gols:</b>
  <%= @classificacao.gols %>
</p>

<p>
  <b>Golscontra:</b>
  <%= @classificacao.golscontra %>
</p>

<p>
  <b>Saldogols:</b>
  <%= @classificacao.saldogols %>
</p>


<%= link_to 'Edit', edit_classificacao_path(@classificacao) %> |
<%= link_to 'Back', classificacaos_path %>