config/routes.rb
Bolao::Application.routes.draw do
  resources :classificacaos

  resources :palpites

  resources :usuarios

  resources :jogos

  resources :clubes
	
  get "home/index"
  get "bolao" => 'bolao#index'

    root :to => 'home#index'

end

app/models/palpite.rb
class Palpite < ActiveRecord::Base
  attr_accessible :gol_mandante, :gol_visitante, :id_jogo, :id_palpite, :id_usuario
   validates :gol_mandante, :presence => true
   validates :gol_visitante, :presence => true
   validates :id_jogo, :presence => true
end

app/controllers/palpites_controller.rb
class PalpitesController < ApplicationController
  # GET /palpites
  # GET /palpites.json
  def index
    @palpites = Palpite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @palpites }
    end
  end

  # GET /palpites/1
  # GET /palpites/1.json
  def show
    @palpite = Palpite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @palpite }
    end
  end

  # GET /palpites/new
  # GET /palpites/new.json
  def new
    @palpite = Palpite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @palpite }
    end
  end

  # GET /palpites/1/edit
  def edit
    @palpite = Palpite.find(params[:id])
  end

  # POST /palpites
  # POST /palpites.json
  def create
    @palpite = Palpite.new(params[:palpite])

    respond_to do |format|
      if @palpite.save
        format.html { redirect_to @palpite, :notice => 'Palpite was successfully created.' }
        format.json { render :json => @palpite, :status => :created, :location => @palpite }
      else
        format.html { render :action => "new" }
        format.json { render :json => @palpite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /palpites/1
  # PUT /palpites/1.json
  def update
    @palpite = Palpite.find(params[:id])

    respond_to do |format|
      if @palpite.update_attributes(params[:palpite])
        format.html { redirect_to @palpite, :notice => 'Palpite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @palpite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /palpites/1
  # DELETE /palpites/1.json
  def destroy
    @palpite = Palpite.find(params[:id])
    @palpite.destroy

    respond_to do |format|
      format.html { redirect_to palpites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/palpites_helper.rb
module PalpitesHelper
end

app/views/palpites/_form.html.erb
<%= form_for(@palpite) do |f| %>
  <% if @palpite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@palpite.errors.count, "error") %> prohibited this palpite from being saved:</h2>

      <ul>
      <% @palpite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_palpite %><br />
    <%= f.number_field :id_palpite %>
  </div>
  <div class="field">
    <%= f.label :id_jogo %><br />
    <%= f.number_field :id_jogo %>
  </div>
  <div class="field">
    <%= f.label :id_usuario %><br />
    <%= f.number_field :id_usuario %>
  </div>
  <div class="field">
    <%= f.label :gol_mandante %><br />
    <%= f.number_field :gol_mandante %>
  </div>
  <div class="field">
    <%= f.label :gol_visitante %><br />
    <%= f.number_field :gol_visitante %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/palpites/edit.html.erb
<h1>Editar palpite</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @palpite %> |
<%= link_to 'Voltar', palpites_path %>

app/views/palpites/index.html.erb
<h1>Todos os palpites</h1>

<table>
  <tr>
    <th>Rodada</th>
    <th>ID Jogo</th>
    <th>Id usuario</th>
    <th>Gol mandante</th>
    <th>Gol visitante</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @palpites.each do |palpite| %>
  <tr>
    <td><%= palpite.id_palpite %></td>
    <td><%= palpite.id_jogo %></td>
    <td><%= palpite.id_usuario %></td>
    <td><%= palpite.gol_mandante %></td>
    <td><%= palpite.gol_visitante %></td>
    <td><%= link_to 'Show', palpite %></td>
    <td><%= link_to 'Edit', edit_palpite_path(palpite) %></td>
    <td><%= link_to 'Destroy', palpite, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Palpite', new_palpite_path %>

app/views/palpites/new.html.erb
<h1>New palpite</h1>

<%= render 'form' %>

<%= link_to 'Back', palpites_path %>

app/views/palpites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id palpite:</b>
  <%= @palpite.id_palpite %>
</p>

<p>
  <b>Id jogo:</b>
  <%= @palpite.id_jogo %>
</p>

<p>
  <b>Id usuario:</b>
  <%= @palpite.id_usuario %>
</p>

<p>
  <b>Gol mandante:</b>
  <%= @palpite.gol_mandante %>
</p>

<p>
  <b>Gol visitante:</b>
  <%= @palpite.gol_visitante %>
</p>


<%= link_to 'Edit', edit_palpite_path(@palpite) %> |
<%= link_to 'Back', palpites_path %>