config/routes.rb
Bolao::Application.routes.draw do
  resources :classificacaos

  resources :palpites

  resources :usuarios

  resources :jogos

  resources :clubes
	
  get "home/index"
  get "bolao" => 'bolao#index'

    root :to => 'home#index'

end

app/models/jogo.rb
class Jogo < ActiveRecord::Base
  attr_accessible :gols_mandante, :gols_visitante, :id_jogo, :time_mandante, :time_visitante
   validates :gols_mandante, :presence => true
   validates :gols_visitante, :presence => true
   validates :id_jogo, :presence => true
   validates :time_mandante, :presence => true
   validates :time_visitante, :presence => true
end

app/controllers/jogos_controller.rb
class JogosController < ApplicationController
  # GET /jogos
  # GET /jogos.json
  def index
    @jogos = Jogo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @jogos }
    end
  end

  # GET /jogos/1
  # GET /jogos/1.json
  def show
    @jogo = Jogo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @jogo }
    end
  end

  # GET /jogos/new
  # GET /jogos/new.json
  def new
    @jogo = Jogo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @jogo }
    end
  end

  # GET /jogos/1/edit
  def edit
    @jogo = Jogo.find(params[:id])
  end

  # POST /jogos
  # POST /jogos.json
  def create
    @jogo = Jogo.new(params[:jogo])

    respond_to do |format|
      if @jogo.save
        format.html { redirect_to @jogo, :notice => 'Jogo was successfully created.' }
        format.json { render :json => @jogo, :status => :created, :location => @jogo }
      else
        format.html { render :action => "new" }
        format.json { render :json => @jogo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /jogos/1
  # PUT /jogos/1.json
  def update
    @jogo = Jogo.find(params[:id])

    respond_to do |format|
      if @jogo.update_attributes(params[:jogo])
        format.html { redirect_to @jogo, :notice => 'Jogo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @jogo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /jogos/1
  # DELETE /jogos/1.json
  def destroy
    @jogo = Jogo.find(params[:id])
    @jogo.destroy

    respond_to do |format|
      format.html { redirect_to jogos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/jogos_helper.rb
module JogosHelper
end

app/views/jogos/_form.html.erb
<%= form_for(@jogo) do |f| %>
  <% if @jogo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jogo.errors.count, "error") %> prohibited this jogo from being saved:</h2>

      <ul>
      <% @jogo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_jogo %><br />
    <%= f.number_field :id_jogo %>
  </div>
  <div class="field">
    <%= f.label :time_mandante %><br />
    <%= f.number_field :time_mandante %><br />
  </div>
  <div class="field">
    <%= f.label :time_visitante %><br />
    <%= f.text_field :time_visitante %>
  </div>
  <div class="field">
    <%= f.label :gols_mandante %><br />
    <%= f.text_field :gols_mandante %>
  </div>
  <div class="field">
    <%= f.label :gols_visitante %><br />
    <%= f.text_field :gols_visitante %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jogos/edit.html.erb
<h1>Editing jogo</h1>

<%= render 'form' %>

<%= link_to 'Show', @jogo %> |
<%= link_to 'Back', jogos_path %>

app/views/jogos/index.html.erb
<h1>Todos os Jogos do campeonato:</h1>

<table>
  <tr>
    <th>Rodada</th>
    <th>Time mandante</th>
    <th>Time visitante</th>
    <th>Gols mandante</th>
    <th>Gols visitante</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jogos.each do |jogo| %>
  <tr>
    <td><%= jogo.id_jogo %></td>
    <td><%= jogo.time_mandante %></td>
    <td><%= jogo.time_visitante %></td>
    <td><%= jogo.gols_mandante %></td>
    <td><%= jogo.gols_visitante %></td>
    <td><%= link_to 'Visualizar', jogo %></td>
    <td><%= link_to 'Editar', edit_jogo_path(jogo) %></td>
    <td><%= link_to 'Apagar', jogo, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Inserir Jogo', new_jogo_path %>

app/views/jogos/new.html.erb
<h1>New jogo</h1>

<%= render 'form' %>

<%= link_to 'Back', jogos_path %>

app/views/jogos/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Partida</h1>

<p>
  <b>Rodada:</b>
  <%= @jogo.id_jogo %>
</p>

<p>
  <b>Time mandante:</b>
  <%= @jogo.time_mandante %>
</p>

<p>
  <b>Time visitante:</b>
  <%= @jogo.time_visitante %>
</p>

<p>
  <b>Gols mandante:</b>
  <%= @jogo.gols_mandante %>
</p>

<p>
  <b>Gols visitante:</b>
  <%= @jogo.gols_visitante %>
</p>


<%= link_to 'Edit', edit_jogo_path(@jogo) %> |
<%= link_to 'Back', jogos_path %>