config/routes.rb
Bolao::Application.routes.draw do
  resources :classificacaos

  resources :palpites

  resources :usuarios

  resources :jogos

  resources :clubes
	
  get "home/index"
  get "bolao" => 'bolao#index'

    root :to => 'home#index'

end

app/models/clube.rb
class Clube < ActiveRecord::Base
  attr_accessible :descricao, :estadio, :id, :nome
   validates :descricao, :presence => true
   validates :estadio, :presence => true
   validates :nome, :presence => true
end

app/controllers/clubes_controller.rb
class ClubesController < ApplicationController
  # GET /clubes
  # GET /clubes.json
  def index
    @clubes = Clube.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clubes }
    end
  end

  # GET /clubes/1
  # GET /clubes/1.json
  def show
    @clube = Clube.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @clube }
    end
  end

  # GET /clubes/new
  # GET /clubes/new.json
  def new
    @clube = Clube.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @clube }
    end
  end

  # GET /clubes/1/edit
  def edit
    @clube = Clube.find(params[:id])
  end

  # POST /clubes
  # POST /clubes.json
  def create
    @clube = Clube.new(params[:clube])

    respond_to do |format|
      if @clube.save
        format.html { redirect_to @clube, :notice => 'Clube was successfully created.' }
        format.json { render :json => @clube, :status => :created, :location => @clube }
      else
        format.html { render :action => "new" }
        format.json { render :json => @clube.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clubes/1
  # PUT /clubes/1.json
  def update
    @clube = Clube.find(params[:id])

    respond_to do |format|
      if @clube.update_attributes(params[:clube])
        format.html { redirect_to @clube, :notice => 'Clube was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @clube.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clubes/1
  # DELETE /clubes/1.json
  def destroy
    @clube = Clube.find(params[:id])
    @clube.destroy

    respond_to do |format|
      format.html { redirect_to clubes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clubes_helper.rb
module ClubesHelper
end

app/views/clubes/_form.html.erb
<%= form_for(@clube) do |f| %>
  <% if @clube.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clube.errors.count, "error") %> prohibited this clube from being saved:</h2>

      <ul>
      <% @clube.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :estadio %><br />
    <%= f.text_field :estadio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clubes/edit.html.erb
<h1>Editing clube</h1>

<%= render 'form' %>

<%= link_to 'Show', @clube %> |
<%= link_to 'Back', clubes_path %>

app/views/clubes/index.html.erb
<h1>Listing clubes</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Nome</th>
    <th>Descricao</th>
    <th>Estadio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clubes.each do |clube| %>
  <tr>
    <td><%= clube.id %></td>
    <td><%= clube.nome %></td>
    <td><%= clube.descricao %></td>
    <td><%= clube.estadio %></td>
    <td><%= link_to 'Show', clube %></td>
    <td><%= link_to 'Edit', edit_clube_path(clube) %></td>
    <td><%= link_to 'Destroy', clube, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Clube', new_clube_path %>

app/views/clubes/new.html.erb
<h1>New clube</h1>

<%= render 'form' %>

<%= link_to 'Back', clubes_path %>

app/views/clubes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @clube.id %>
</p>

<p>
  <b>Nome:</b>
  <%= @clube.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @clube.descricao %>
</p>

<p>
  <b>Estadio:</b>
  <%= @clube.estadio %>
</p>


<%= link_to 'Edit', edit_clube_path(@clube) %> |
<%= link_to 'Back', clubes_path %>